In [113]:
# import pandas and seaborn
import pandas as pd
import seaborn as sns

In [114]:
df = pd.read_csv("Data/e-commerce.csv")

In [115]:
df.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN

In [116]:
df.columns

Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='str')

In [117]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3986 entries, 0 to 3985
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       40 non-null     str
 1   goods-title-link--jump href  40 non-null     str
 2   rank-title                   559 non-null    str
 3   rank-sub                     559 non-null    str
 4   price                        3986 non-null   str
 5   discount                     2459 non-null   str
 6   selling_proposition          1361 non-null   str
 7   goods-title-link             3946 non-null   str
dtypes: str(8)
memory usage: 249.3 KB

In [118]:
# check null values
df.isnull().sum()/len(df)*100

goods-title-link--jump         98.996488
goods-title-link--jump href    98.996488
rank-title                     85.975916
rank-sub                       85.975916
price                           0.000000
discount                       38.309082
selling_proposition            65.855494
goods-title-link                1.003512
dtype: float64

In [119]:
df['goods-title-link'].isnull().value_counts()

goods-title-link
False    3946
True       40
Name: count, dtype: int64

In [120]:
df.drop(columns=['goods-title-link'], inplace=True)

In [121]:
df.columns

Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition'],
      dtype='str')

### Clean Price

In [122]:
df['price'] = (df['price'].str.replace('$' , '', regex=False).str.replace(',', '', regex=False)).astype(float)

Clean Discount Column

In [123]:
df['discount']

0       -22%
1       -20%
2        NaN
3       -72%
4       -40%
        ...
3981     NaN
3982     NaN
3983    -24%
3984     -3%
3985    -28%
Name: discount, Length: 3986, dtype: str

In [124]:
df['discount'] = df['discount'].str.replace('%', '', regex=False)
df['discount'] = df['discount'].str.replace('-', '', regex=False)
df['discount'] = pd.to_numeric(df['discount'], errors= 'coerce')

In [125]:
df['discount']

0       22.0
1       20.0
2        NaN
3       72.0
4       40.0
        ...
3981     NaN
3982     NaN
3983    24.0
3984     3.0
3985    28.0
Name: discount, Length: 3986, dtype: float64

Handle Missing Values

In [126]:
df.isnull().sum()

goods-title-link--jump         3946
goods-title-link--jump href    3946
rank-title                     3427
rank-sub                       3427
price                             0
discount                       1527
selling_proposition            2625
dtype: int64

In [127]:
df['discount'] = df['discount'].fillna(0)

In [128]:
df['discount']

0       22.0
1       20.0
2        0.0
3       72.0
4       40.0
        ...
3981     0.0
3982     0.0
3983    24.0
3984     3.0
3985    28.0
Name: discount, Length: 3986, dtype: float64

In [129]:
df['rank-title']

0       #1 Best Sellers
1       #4 Best Sellers
2                   NaN
3                   NaN
4       #6 Best Sellers
             ...
3981                NaN
3982                NaN
3983                NaN
3984                NaN
3985                NaN
Name: rank-title, Length: 3986, dtype: str

In [130]:
df['rank-title'] = df['rank-title'].fillna('No Rank')

In [131]:
df['rank-title']

0       #1 Best Sellers
1       #4 Best Sellers
2               No Rank
3               No Rank
4       #6 Best Sellers
             ...
3981            No Rank
3982            No Rank
3983            No Rank
3984            No Rank
3985            No Rank
Name: rank-title, Length: 3986, dtype: str

Exract Sales Number

In [132]:
df['selling_proposition']

0                       NaN
1                       NaN
2        400+ sold recently
3       5.6k+ sold recently
4                       NaN
               ...
3981                    NaN
3982                    NaN
3983                    NaN
3984                    NaN
3985                    NaN
Name: selling_proposition, Length: 3986, dtype: str

In [133]:
df['sold_count'] = df['selling_proposition'].str.extract(r'([\d\.]+k?)')

In [134]:
df['sold_count']

0        NaN
1        NaN
2        400
3       5.6k
4        NaN
        ...
3981     NaN
3982     NaN
3983     NaN
3984     NaN
3985     NaN
Name: sold_count, Length: 3986, dtype: str

In [135]:
def convert_k(x):
    if pd.isna(x):
        return 0   

    x = str(x)    

    if 'k' in x:
        return float(x.replace('k', '')) * 1000

    return float(x)

df['sold_count'] = df['sold_count'].apply(convert_k)

In [136]:
df['sold_count']

0          0.0
1          0.0
2        400.0
3       5600.0
4          0.0
         ...
3981       0.0
3982       0.0
3983       0.0
3984       0.0
3985       0.0
Name: sold_count, Length: 3986, dtype: float64

In [137]:
df.columns

Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition', 'sold_count'],
      dtype='str')

In [138]:
df.drop(columns=['selling_proposition'], inplace=True)

In [139]:
df.columns

Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'sold_count'],
      dtype='str')

Clean Product Title

In [155]:
df['product_title'] = df['product_title'].fillna('Unknown Product')

In [156]:
df['product_title']

0       1pc Rechargeable Deep Tissue Muscle Hand
1                  1pc Portable Hanging Neck Fan
2       1pc Pink Colored Curved Eyelash Curler F
3       1 Mini Portable Handheld Fan With 2 Aa B
4       Wit Water Flosser,Portable Oral Irrigato
                          ...
3981                             Unknown Product
3982                             Unknown Product
3983                             Unknown Product
3984                             Unknown Product
3985                             Unknown Product
Name: product_title, Length: 3986, dtype: str

In [157]:
df

,goods-title-link--jump href,rank-title,rank-sub,price,discount,sold_count,product_title
0,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,2.03,22.0,0.0,1pc Rechargeable Deep Tissue Muscle Hand
1,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,6.48,20.0,0.0,1pc Portable Hanging Neck Fan
2,https://us.shein.com/1pc-Pink-Colored-Curved-E...,No Rank,NaN,1.80,0.0,400.0,1pc Pink Colored Curved Eyelash Curler F
3,https://us.shein.com/1-Mini-Portable-Handheld-...,No Rank,NaN,0.88,72.0,5600.0,1 Mini Portable Handheld Fan With 2 Aa B
4,https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,12.06,40.0,0.0,"Wit Water Flosser,Portable Oral Irrigato"
...,...,...,...,...,...,...,...
3981,NaN,No Rank,NaN,54.34,0.0,0.0,Unknown Product
3982,NaN,No Rank,NaN,64.06,0.0,0.0,Unknown Product
3983,NaN,No Rank,NaN,61.99,24.0,0.0,Unknown Product
3984,NaN,No Rank,NaN,81.47,3.0,0.0,Unknown Product
3985,NaN,No Rank,NaN,501.21,28.0,0.0,Unknown Product

Missing URLs

In [158]:
df['goods-title-link--jump href'].isnull().sum()

np.int64(3946)

In [159]:
df['has_url'] = df['goods-title-link--jump href'].notnull()

In [166]:
df.drop(columns=['rank_title_clean'])

,goods-title-link--jump href,rank-title,rank-sub,price,discount,sold_count,product_title,has_url
0,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,2.03,22.0,0.0,1pc Rechargeable Deep Tissue Muscle Hand,True
1,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,6.48,20.0,0.0,1pc Portable Hanging Neck Fan,True
2,https://us.shein.com/1pc-Pink-Colored-Curved-E...,No Rank,NaN,1.80,0.0,400.0,1pc Pink Colored Curved Eyelash Curler F,True
3,https://us.shein.com/1-Mini-Portable-Handheld-...,No Rank,NaN,0.88,72.0,5600.0,1 Mini Portable Handheld Fan With 2 Aa B,True
4,https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,12.06,40.0,0.0,"Wit Water Flosser,Portable Oral Irrigato",True
...,...,...,...,...,...,...,...,...
3981,NaN,No Rank,NaN,54.34,0.0,0.0,Unknown Product,False
3982,NaN,No Rank,NaN,64.06,0.0,0.0,Unknown Product,False
3983,NaN,No Rank,NaN,61.99,24.0,0.0,Unknown Product,False
3984,NaN,No Rank,NaN,81.47,3.0,0.0,Unknown Product,False
3985,NaN,No Rank,NaN,501.21,28.0,0.0,Unknown Product,False

In [167]:
df[['price','discount','sold_count']].dtypes

price         float64
discount      float64
sold_count    float64
dtype: object

In [168]:
df[df['product_title'].isna() & df['goods-title-link--jump href'].isna()]

Empty DataFrame
Columns: [goods-title-link--jump href, rank-title, rank-sub, price, discount, sold_count, product_title, has_url, rank_title_clean]
Index: []

In [169]:
df

,goods-title-link--jump href,rank-title,rank-sub,price,discount,sold_count,product_title,has_url,rank_title_clean
0,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,2.03,22.0,0.0,1pc Rechargeable Deep Tissue Muscle Hand,True,#1 Best Sellers
1,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,6.48,20.0,0.0,1pc Portable Hanging Neck Fan,True,#4 Best Sellers
2,https://us.shein.com/1pc-Pink-Colored-Curved-E...,No Rank,NaN,1.80,0.0,400.0,1pc Pink Colored Curved Eyelash Curler F,True,No Rank
3,https://us.shein.com/1-Mini-Portable-Handheld-...,No Rank,NaN,0.88,72.0,5600.0,1 Mini Portable Handheld Fan With 2 Aa B,True,No Rank
4,https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,12.06,40.0,0.0,"Wit Water Flosser,Portable Oral Irrigato",True,#6 Best Sellers
...,...,...,...,...,...,...,...,...,...
3981,NaN,No Rank,NaN,54.34,0.0,0.0,Unknown Product,False,No Rank
3982,NaN,No Rank,NaN,64.06,0.0,0.0,Unknown Product,False,No Rank
3983,NaN,No Rank,NaN,61.99,24.0,0.0,Unknown Product,False,No Rank
3984,NaN,No Rank,NaN,81.47,3.0,0.0,Unknown Product,False,No Rank
3985,NaN,No Rank,NaN,501.21,28.0,0.0,Unknown Product,False,No Rank

In [174]:
clean_df = df[[
    'product_title',
    'goods-title-link--jump href',
    'price',
    'discount',
    'sold_count',
    'rank-title',
]]

In [178]:
clean_df.to_excel('Data/cleaned_data.xlsx', index=False)